name: BackEnd-CI

on:
  push:
    branches: 'feature/*'
  pull_request:
    branches: 'develop'
    types: [labeled, opened, synchronize, reopened]
  
jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, '💻백엔드')
    runs-on: ubuntu-latest

    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: node 세팅
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: 의존성 설치
      run: npm install
      working-directory: ./back-end

    - name: 테스트 진행
      run: npm test
      working-directory: ./back-end